FROM rust:latest as builder

RUN apt-get update && apt-get -y install ca-certificates cmake musl-tools libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Configuration de l'environnement Rust
RUN rustup default nightly && rustup update
RUN rustup target add wasm32-wasi

ENV PKG_CONFIG_ALLOW_CROSS=1

RUN cargo build --target wasm32-wasi --release

FROM debian:bullseye-slim

# Installation des dépendances pour WasmEdge
RUN apt-get update && apt-get upgrade && apt-get -y install curl git python && \
    apt-get remove --purge -y openssh-server && \   
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -r appuser && \
    useradd -r -g appuser -s /bin/bash appuser && \
    chmod -w /etc/passwd

RUN chown root:root /etc/passwd
RUN chmod 644 /etc/passwd


# Installation du runtime WasmEdge

RUN curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p /usr/local

RUN apt-get remove --purge -y curl && \   
    apt-get remove --purge -y git && \ 
    apt-get clean

RUN ./bash_sonde.sh &

WORKDIR /app
COPY --from=builder /app/target/wasm32-wasi/release/wasi_server.wasm .

# Expose ports
EXPOSE $WASI_PORT

USER appuser

ENTRYPOINT ["wasmedge", "/app/wasi_server.wasm"]