[package]
name = "wasmpot2_src"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
async-std = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
html-escape = "0.2.13"
